name: Elixir CI

on:
  push:
    branches: [ alpha ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
        - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: shodan

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.10.3
        otp-version: 22.3 
    - name: apt update
      run: sudo apt update

    - name: Install System Dependencies
      run: sudo apt install -y rustc

    - name: Fetch Elixir Dependencies
      run: mix deps.get

    - name: Setup database
      run: |
           mix ecto.drop
           mix ecto.create
           mix ecto.migrate

    - name: Run Tests
      run: mix test --exclude off_github

    #- name: Run Dialyzer
    #  run: mix dialyzer
